//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Inputs/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""SniperRifle"",
            ""id"": ""66708db1-113a-4746-beee-5ec09412b9d3"",
            ""actions"": [
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""916bc71c-4dfa-44d8-8976-aeac9d937a02"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3eab7035-2fcb-463b-93b8-a98bf5d33184"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a10321aa-51b9-4703-a6c2-601a4abf78a6"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Collector"",
            ""id"": ""7a39878d-c07e-4419-a69f-2c33f57988a0"",
            ""actions"": [
                {
                    ""name"": ""Collect"",
                    ""type"": ""Button"",
                    ""id"": ""db3100f0-f312-470b-8211-10749bee00ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b476aea0-e19c-4b35-868b-3d6b3487fed7"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Collect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""d879bdc7-4db8-4053-a3a4-ddcf82d2e1ba"",
            ""actions"": [
                {
                    ""name"": ""SkipTutorial"",
                    ""type"": ""Button"",
                    ""id"": ""20226536-d6f0-4ccb-b9b9-63f147970599"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5d2e0413-1bd3-4378-a9fd-10d0e87fdd03"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipTutorial"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""GameManager"",
            ""id"": ""527b7460-9ed6-4c74-aa6e-2056dc4d5146"",
            ""actions"": [
                {
                    ""name"": ""Quit"",
                    ""type"": ""Button"",
                    ""id"": ""12022cb5-7dd1-4ea6-8d84-7ad912988567"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""188bae7b-954c-409b-9d3e-f23cc94a866c"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""f9ad3f91-bfa1-4e1f-b8e1-11a23c24208f"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""e5b2cba8-e376-4b6f-8039-db2e5c3a404d"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SniperRifle
        m_SniperRifle = asset.FindActionMap("SniperRifle", throwIfNotFound: true);
        m_SniperRifle_Fire = m_SniperRifle.FindAction("Fire", throwIfNotFound: true);
        // Collector
        m_Collector = asset.FindActionMap("Collector", throwIfNotFound: true);
        m_Collector_Collect = m_Collector.FindAction("Collect", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_SkipTutorial = m_UI.FindAction("SkipTutorial", throwIfNotFound: true);
        // GameManager
        m_GameManager = asset.FindActionMap("GameManager", throwIfNotFound: true);
        m_GameManager_Quit = m_GameManager.FindAction("Quit", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SniperRifle
    private readonly InputActionMap m_SniperRifle;
    private List<ISniperRifleActions> m_SniperRifleActionsCallbackInterfaces = new List<ISniperRifleActions>();
    private readonly InputAction m_SniperRifle_Fire;
    public struct SniperRifleActions
    {
        private @PlayerInputActions m_Wrapper;
        public SniperRifleActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Fire => m_Wrapper.m_SniperRifle_Fire;
        public InputActionMap Get() { return m_Wrapper.m_SniperRifle; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SniperRifleActions set) { return set.Get(); }
        public void AddCallbacks(ISniperRifleActions instance)
        {
            if (instance == null || m_Wrapper.m_SniperRifleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SniperRifleActionsCallbackInterfaces.Add(instance);
            @Fire.started += instance.OnFire;
            @Fire.performed += instance.OnFire;
            @Fire.canceled += instance.OnFire;
        }

        private void UnregisterCallbacks(ISniperRifleActions instance)
        {
            @Fire.started -= instance.OnFire;
            @Fire.performed -= instance.OnFire;
            @Fire.canceled -= instance.OnFire;
        }

        public void RemoveCallbacks(ISniperRifleActions instance)
        {
            if (m_Wrapper.m_SniperRifleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISniperRifleActions instance)
        {
            foreach (var item in m_Wrapper.m_SniperRifleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SniperRifleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SniperRifleActions @SniperRifle => new SniperRifleActions(this);

    // Collector
    private readonly InputActionMap m_Collector;
    private List<ICollectorActions> m_CollectorActionsCallbackInterfaces = new List<ICollectorActions>();
    private readonly InputAction m_Collector_Collect;
    public struct CollectorActions
    {
        private @PlayerInputActions m_Wrapper;
        public CollectorActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Collect => m_Wrapper.m_Collector_Collect;
        public InputActionMap Get() { return m_Wrapper.m_Collector; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CollectorActions set) { return set.Get(); }
        public void AddCallbacks(ICollectorActions instance)
        {
            if (instance == null || m_Wrapper.m_CollectorActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CollectorActionsCallbackInterfaces.Add(instance);
            @Collect.started += instance.OnCollect;
            @Collect.performed += instance.OnCollect;
            @Collect.canceled += instance.OnCollect;
        }

        private void UnregisterCallbacks(ICollectorActions instance)
        {
            @Collect.started -= instance.OnCollect;
            @Collect.performed -= instance.OnCollect;
            @Collect.canceled -= instance.OnCollect;
        }

        public void RemoveCallbacks(ICollectorActions instance)
        {
            if (m_Wrapper.m_CollectorActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICollectorActions instance)
        {
            foreach (var item in m_Wrapper.m_CollectorActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CollectorActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CollectorActions @Collector => new CollectorActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_SkipTutorial;
    public struct UIActions
    {
        private @PlayerInputActions m_Wrapper;
        public UIActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @SkipTutorial => m_Wrapper.m_UI_SkipTutorial;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @SkipTutorial.started += instance.OnSkipTutorial;
            @SkipTutorial.performed += instance.OnSkipTutorial;
            @SkipTutorial.canceled += instance.OnSkipTutorial;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @SkipTutorial.started -= instance.OnSkipTutorial;
            @SkipTutorial.performed -= instance.OnSkipTutorial;
            @SkipTutorial.canceled -= instance.OnSkipTutorial;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);

    // GameManager
    private readonly InputActionMap m_GameManager;
    private List<IGameManagerActions> m_GameManagerActionsCallbackInterfaces = new List<IGameManagerActions>();
    private readonly InputAction m_GameManager_Quit;
    public struct GameManagerActions
    {
        private @PlayerInputActions m_Wrapper;
        public GameManagerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Quit => m_Wrapper.m_GameManager_Quit;
        public InputActionMap Get() { return m_Wrapper.m_GameManager; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameManagerActions set) { return set.Get(); }
        public void AddCallbacks(IGameManagerActions instance)
        {
            if (instance == null || m_Wrapper.m_GameManagerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameManagerActionsCallbackInterfaces.Add(instance);
            @Quit.started += instance.OnQuit;
            @Quit.performed += instance.OnQuit;
            @Quit.canceled += instance.OnQuit;
        }

        private void UnregisterCallbacks(IGameManagerActions instance)
        {
            @Quit.started -= instance.OnQuit;
            @Quit.performed -= instance.OnQuit;
            @Quit.canceled -= instance.OnQuit;
        }

        public void RemoveCallbacks(IGameManagerActions instance)
        {
            if (m_Wrapper.m_GameManagerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameManagerActions instance)
        {
            foreach (var item in m_Wrapper.m_GameManagerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameManagerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GameManagerActions @GameManager => new GameManagerActions(this);
    public interface ISniperRifleActions
    {
        void OnFire(InputAction.CallbackContext context);
    }
    public interface ICollectorActions
    {
        void OnCollect(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnSkipTutorial(InputAction.CallbackContext context);
    }
    public interface IGameManagerActions
    {
        void OnQuit(InputAction.CallbackContext context);
    }
}
