//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Inputs/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""SniperRifle"",
            ""id"": ""66708db1-113a-4746-beee-5ec09412b9d3"",
            ""actions"": [
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""916bc71c-4dfa-44d8-8976-aeac9d937a02"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3eab7035-2fcb-463b-93b8-a98bf5d33184"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Collector"",
            ""id"": ""7a39878d-c07e-4419-a69f-2c33f57988a0"",
            ""actions"": [
                {
                    ""name"": ""Collect"",
                    ""type"": ""Button"",
                    ""id"": ""db3100f0-f312-470b-8211-10749bee00ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b476aea0-e19c-4b35-868b-3d6b3487fed7"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Collect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SniperRifle
        m_SniperRifle = asset.FindActionMap("SniperRifle", throwIfNotFound: true);
        m_SniperRifle_Fire = m_SniperRifle.FindAction("Fire", throwIfNotFound: true);
        // Collector
        m_Collector = asset.FindActionMap("Collector", throwIfNotFound: true);
        m_Collector_Collect = m_Collector.FindAction("Collect", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SniperRifle
    private readonly InputActionMap m_SniperRifle;
    private List<ISniperRifleActions> m_SniperRifleActionsCallbackInterfaces = new List<ISniperRifleActions>();
    private readonly InputAction m_SniperRifle_Fire;
    public struct SniperRifleActions
    {
        private @PlayerInputActions m_Wrapper;
        public SniperRifleActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Fire => m_Wrapper.m_SniperRifle_Fire;
        public InputActionMap Get() { return m_Wrapper.m_SniperRifle; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SniperRifleActions set) { return set.Get(); }
        public void AddCallbacks(ISniperRifleActions instance)
        {
            if (instance == null || m_Wrapper.m_SniperRifleActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SniperRifleActionsCallbackInterfaces.Add(instance);
            @Fire.started += instance.OnFire;
            @Fire.performed += instance.OnFire;
            @Fire.canceled += instance.OnFire;
        }

        private void UnregisterCallbacks(ISniperRifleActions instance)
        {
            @Fire.started -= instance.OnFire;
            @Fire.performed -= instance.OnFire;
            @Fire.canceled -= instance.OnFire;
        }

        public void RemoveCallbacks(ISniperRifleActions instance)
        {
            if (m_Wrapper.m_SniperRifleActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISniperRifleActions instance)
        {
            foreach (var item in m_Wrapper.m_SniperRifleActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SniperRifleActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SniperRifleActions @SniperRifle => new SniperRifleActions(this);

    // Collector
    private readonly InputActionMap m_Collector;
    private List<ICollectorActions> m_CollectorActionsCallbackInterfaces = new List<ICollectorActions>();
    private readonly InputAction m_Collector_Collect;
    public struct CollectorActions
    {
        private @PlayerInputActions m_Wrapper;
        public CollectorActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Collect => m_Wrapper.m_Collector_Collect;
        public InputActionMap Get() { return m_Wrapper.m_Collector; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CollectorActions set) { return set.Get(); }
        public void AddCallbacks(ICollectorActions instance)
        {
            if (instance == null || m_Wrapper.m_CollectorActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CollectorActionsCallbackInterfaces.Add(instance);
            @Collect.started += instance.OnCollect;
            @Collect.performed += instance.OnCollect;
            @Collect.canceled += instance.OnCollect;
        }

        private void UnregisterCallbacks(ICollectorActions instance)
        {
            @Collect.started -= instance.OnCollect;
            @Collect.performed -= instance.OnCollect;
            @Collect.canceled -= instance.OnCollect;
        }

        public void RemoveCallbacks(ICollectorActions instance)
        {
            if (m_Wrapper.m_CollectorActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICollectorActions instance)
        {
            foreach (var item in m_Wrapper.m_CollectorActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CollectorActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CollectorActions @Collector => new CollectorActions(this);
    public interface ISniperRifleActions
    {
        void OnFire(InputAction.CallbackContext context);
    }
    public interface ICollectorActions
    {
        void OnCollect(InputAction.CallbackContext context);
    }
}
